### ISSUE TITLE
No support for com.github.robtimus.filesystems.FileSystemProviderSupport.

### ISSUE THREAD

**Issue by ziplokk1** [robtimus/fs-core#1]
Any particular reason that it's unsupported? Just curious to see if I can help somehow.

Thanks.

**Comment by rob-spoor** [comment]
Can you please elaborate on what you're missing?

**Comment by ziplokk1** [comment]
Oops, completely forgot to mention that... I'm needing the `position` method to be supported.

**Comment by robtimus** [comment]
For a generic InputStream it's not possible to go to an earlier position unless all of its contents are cached. For a generic OutputStream it's not possible to go to an earlier position and overwrite contents unless all of its contents are cached and only flushed upon closing. Both solutions will not be memory efficient.

The only reason I wrote these methods in the first place is because of the `FileSystem.newByteChannel` method. Perhaps I should have made those methods throw an exception, but I chose to support parts of it instead of nothing at all.
